version: "3.6"
services:

  haproxy:
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.1.55:24224
        fluentd-async-connect: "true"
        tag: haproxy 

  apache01:
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.1.55:24224
        fluentd-async-connect: "true"
        tag: apache 

  apache02:
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.1.55:24224
        fluentd-async-connect: "true"
        tag: apache 

