version: "3.6"
services:

 init:
    image: jboss
    build: ./jboss
    command: init
    networks:
      - jbossnet
    volumes:
      - ./repositorio:/opt/repositorio
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

