version: "3.6"
services:

  haproxy:
    build: ./haproxy
    hostname: haproxy
    restart: unless-stopped
    volumes:
      - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/custom_404.html:/etc/haproxy/errors/custom_404.html:ro
    cap_add:
      - NET_ADMIN
    networks:
      - contingencia 
 
  apache01:
    image: apache
    build: ./apache
    hostname: apache01
    restart: unless-stopped
    volumes:
      - ./apache/cluster.conf:/etc/apache2/conf-available/cluster.conf:ro
      - ./apache/site.conf:/etc/apache2/sites-enabled/site.conf:ro
      - ./apache/apache2.conf:/etc/apache2/apache2.conf:ro
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    cap_add:
      - NET_ADMIN
    networks:
      - contingencia 
 
  apache02:
    image: apache
    build: ./apache
    hostname: apache02
    restart: unless-stopped
    volumes:
      - ./apache/cluster.conf:/etc/apache2/conf-available/cluster.conf:ro
      - ./apache/site.conf:/etc/apache2/sites-enabled/site.conf:ro
      - ./apache/apache2.conf:/etc/apache2/apache2.conf:ro
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    cap_add:
      - NET_ADMIN
    networks:
      - contingencia 
 
  memcached:
    image: memcached:1.6-alpine
    command: -m 256m
    hostname: memcached
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - contingencia 
 
  master:
    image: jboss
    build: ./jboss
    command: master
    hostname: master
    volumes:
      - ./jboss/fluent.conf:/etc/fluent/fluent.conf
      - jboss-data:/opt/data
      - ./jboss:/mnt/share
      - ./repositorio:/opt/repositorio
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - contingencia 
 
  slave01:
    image: jboss
    build: ./jboss
    command: slave
    hostname: slave01
    scale: 1
    depends_on:
      - master
    networks:
      - contingencia 
    volumes:
      - ./jboss/fluent.conf:/etc/fluent/fluent.conf
      - jboss-data:/opt/data
      - ./jboss:/mnt/share
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  slave02:
    image: jboss
    build: ./jboss
    command: slave
    hostname: slave02
    scale: 1 
    depends_on:
      - master
    networks:
      - contingencia 
    volumes:
      - ./jboss/fluent.conf:/etc/fluent/fluent.conf
      - jboss-data:/opt/data
      - ./jboss:/mnt/share
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  slave03:
    image: jboss
    build: ./jboss
    command: slave
    hostname: slave03
    scale: 1
    depends_on:
      - master
    networks:
      - contingencia 
    volumes:
      - ./jboss/fluent.conf:/etc/fluent/fluent.conf
      - jboss-data:/opt/data
      - ./jboss:/mnt/share
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  firefox:
    image: lscr.io/linuxserver/firefox
    hostname: firefox 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    networks:
      - contingencia 
    scale: 0
    links:
      - "haproxy:domainmodelab"
    shm_size: "1gb"
    restart: unless-stopped

networks:
  contingencia:

volumes:
  jboss-data:

