version: "3.6"
services:

  haproxy:
    image: haproxytech/haproxy-ubuntu:2.2
#    image: haproxy:2.2
#    build: ./haproxy
    hostname: haproxy
    restart: unless-stopped
    networks:
      - jbossnet
    volumes:
      - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/custom_404.html:/etc/haproxy/errors/custom_404.html:ro
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    cap_add:
      - NET_ADMIN

  apache01:
    image: apache 
    build: ./apache
    hostname: apache01
    restart: unless-stopped
    volumes:
      - ./apache/cluster.conf:/etc/apache2/conf-available/cluster.conf 
    networks:
      - jbossnet
    depends_on:
      - fluentd 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  apache02:
    image: apache 
    build: ./apache
    hostname: apache02
    restart: unless-stopped
    volumes:
      - ./apache/cluster.conf:/etc/apache2/conf-available/cluster.conf 
    networks:
      - jbossnet
    depends_on:
      - fluentd 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  master:
    image: jboss
    build: ./jboss
    command: master
    hostname: master
    networks:
      - jbossnet
    volumes:
      - jboss-data:/opt/data
      - ./jboss:/mnt/share
      - ./repositorio:/opt/repositorio
#      - ./jboss/domain.xml:/opt/jboss/domain/configuration/domain.xml:rw
#      - ./jboss/host-master.xml:/opt/jboss/domain/configuration/host-master.xml
#      - ./jboss/host-slave.xml:/opt/jboss/domain/configuration/host-slave.xml
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  backup:
    image: jboss
    build: ./jboss
    command: master
    hostname: backup
    networks:
      - jbossnet
    scale: 0 
    volumes:
      - jboss-data:/opt/data
      - ./jboss:/mnt/share
#      - ./jboss/domain.xml:/opt/jboss/domain/configuration/domain.xml:rw
#      - ./jboss/host-master.xml:/opt/jboss/domain/configuration/host-master.xml
#      - ./jboss/host-slave.xml:/opt/jboss/domain/configuration/host-slave.xml
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  slave01:
    image: jboss
    build: ./jboss
    command: slave
    hostname: slave01
    scale: 1
    depends_on:
      - master
    networks:
      - jbossnet
    volumes:
      - jboss-data:/opt/data
      - ./jboss:/mnt/share
#      - ./jboss/domain.xml:/opt/jboss/domain/configuration/domain.xml
#      - ./jboss/host-master.xml:/opt/jboss/domain/configuration/host-master.xml
#      - ./jboss/host-slave.xml:/opt/jboss/domain/configuration/host-slave.xml:rw
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  slave02:
    image: jboss
    build: ./jboss
    command: slave
    hostname: slave02
    scale: 1 
    depends_on:
      - master
    networks:
      - jbossnet
    volumes:
      - jboss-data:/opt/data
      - ./jboss:/mnt/share
#      - ./jboss/domain.xml:/opt/jboss/domain/configuration/domain.xml
#      - ./jboss/host-master.xml:/opt/jboss/domain/configuration/host-master.xml
#      - ./jboss/host-slave.xml:/opt/jboss/domain/configuration/host-slave.xml:rw
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  slave03:
    image: jboss
    build: ./jboss
    command: slave
    hostname: slave03
    scale: 1
    depends_on:
      - master
    networks:
      - jbossnet
    volumes:
      - jboss-data:/opt/data
      - ./jboss:/mnt/share
#      - ./jboss/domain.xml:/opt/jboss/domain/configuration/domain.xml
#      - ./jboss/host-master.xml:/opt/jboss/domain/configuration/host-master.xml
#      - ./jboss/host-slave.xml:/opt/jboss/domain/configuration/host-slave.xml:rw
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  fluentd:
    image:  fluent/fluentd
    hostname: fluentd
    scale: 0
    volumes:
      - ./fluentd:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - jbossnet

  firefox:
    image: lscr.io/linuxserver/firefox
    hostname: firefox 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
#    volumes:
#      - /path/to/config:/config
    networks:
      - jbossnet
    scale: 0
    links:
      - "haproxy:jbosslab"
    shm_size: "1gb"
    restart: unless-stopped

#  desktop:
#    image: desktop
#    build: ./desktop
#    hostname: desktop
#    scale: 0
#    networks:
#      - jbossnet
#    volumes:
#      - /home/ubuntu/jboss-domain/repositorio:/opt/repositorio
#    sysctls:
#      - net.ipv6.conf.all.disable_ipv6=0

networks:
  jbossnet:
    ipv6: false
  haproxynet:
    driver: bridge

volumes:
  jboss-data:

